/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.HospitalWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.util.logging.*;

/**
 *
 * @author maneesh
 */
public class HospitalAdminJPanel extends javax.swing.JPanel {
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);

    /**
     * Creates new form HospitalAdminJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    EcoSystem business;
    
    public HospitalAdminJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        logr.info("LoggingIn");
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adddoctor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        assigntodoctor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Welcome Hospital Admin ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, -1, 33));

        adddoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adddoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adddoctorMouseClicked(evt);
            }
        });

        jLabel2.setText("ADD DOCTOR");
        adddoctor.add(jLabel2);

        add(adddoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 180, 240));

        assigntodoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assigntodoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assigntodoctorMouseClicked(evt);
            }
        });

        jLabel3.setText("ASSIGN TO DOCTOR");
        assigntodoctor.add(jLabel3);

        add(assigntodoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 180, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/HospitalWorkArea/hospitalimage.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void assigntodoctorMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        AddDoctorPanel addDoctor = new AddDoctorPanel(userProcessContainer,organization);
        userProcessContainer.add("addOrganization",addDoctor);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        logr.info("Assign Doctor Button Clicked");
    }                                        


    private void adddoctorMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        AssignDoctorPanel aDoc = new AssignDoctorPanel(userProcessContainer, organization);
        userProcessContainer.add("addOrganization",aDoc);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        logr.info("Add Doctor Button Clicked");
    }                                        



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adddoctor;
    private javax.swing.JPanel assigntodoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
